#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# TIA-ARCHITECT-CORE EMERGENCY RESTORATION SCRIPT
# ═══════════════════════════════════════════════════════════════════
# Purpose: One-shot script to restore TIA-ARCHITECT-CORE to operational status
# Usage: ./restore_tia_core.sh
# ═══════════════════════════════════════════════════════════════════

set -e  # Exit on error

echo "🧠 TIA-ARCHITECT-CORE EMERGENCY RESTORATION"
echo "════════════════════════════════════════════"
echo ""

# ── Configuration ──────────────────────────────────────────────────
GITHUB_ORG="DJ-Goana-Coding"
HF_ORG="DJ-Goanna-Coding"
REPO_NAME="TIA-ARCHITECT-CORE"
GITHUB_URL="https://github.com/${GITHUB_ORG}/${REPO_NAME}.git"
WORK_DIR="/tmp/tia_core_restore"
TEMPLATE_DIR="$(pwd)/tia-architect-core-templates"

# ── Step 1: Clone Repository ───────────────────────────────────────
echo "📥 Step 1: Cloning ${REPO_NAME}..."
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

if git clone "$GITHUB_URL" "$REPO_NAME"; then
    echo "✅ Repository cloned successfully"
else
    echo "❌ Failed to clone repository"
    exit 1
fi

cd "$REPO_NAME"

# ── Step 2: Backup Current Configuration ──────────────────────────
echo ""
echo "💾 Step 2: Backing up current configuration..."
if [ -f "requirements.txt" ]; then
    cp requirements.txt requirements.txt.backup
    echo "✅ Backed up requirements.txt"
else
    echo "⚠️  No existing requirements.txt found"
fi

# ── Step 3: Copy Python 3.13 Compatible Requirements ──────────────
echo ""
echo "📋 Step 3: Installing Python 3.13 compatible requirements..."
if [ -f "${TEMPLATE_DIR}/requirements.txt" ]; then
    cp "${TEMPLATE_DIR}/requirements.txt" requirements.txt
    echo "✅ Updated requirements.txt with Python 3.13 compatible versions"
    echo ""
    echo "Key changes:"
    echo "  • pandas: 2.0.3 → 2.2.0+ (Python 3.13 compatible)"
    echo "  • numpy: 1.26.4 → 2.0.0+ (Python 3.13 compatible)"
    echo "  • setuptools: added explicitly (≥75.0.0)"
else
    echo "❌ Template requirements.txt not found at ${TEMPLATE_DIR}/requirements.txt"
    echo "Please ensure you're running this from the mapping-and-inventory directory"
    exit 1
fi

# ── Step 4: Commit Changes ────────────────────────────────────────
echo ""
echo "💾 Step 4: Committing changes..."
git config user.name "Citadel Restore Bot"
git config user.email "restore@citadel.local"
git add requirements.txt

if git diff --cached --quiet; then
    echo "⚠️  No changes to commit (requirements.txt already up to date?)"
else
    git commit -m "🔧 COMPATIBILITY FIX: Upgrade pandas/numpy for Python 3.13 - SOVEREIGN PRIORITY

- pandas: 2.0.3 → 2.2.0+ (Python 3.13 compatible)
- numpy: 1.26.4 → 2.0.0+ (Python 3.13 compatible)
- setuptools: ≥75.0.0 (ensures pkg_resources available)

Fixes: ModuleNotFoundError: No module named 'pkg_resources'
Priority: SOVEREIGN LEVEL
Generated by: Citadel Architect v25.0.OMNI+"
    
    echo "✅ Changes committed"
fi

# ── Step 5: Push to GitHub ────────────────────────────────────────
echo ""
echo "📤 Step 5: Pushing to GitHub..."
if git push origin main; then
    echo "✅ Pushed to GitHub successfully"
else
    echo "❌ Failed to push to GitHub"
    echo "You may need to push manually with credentials"
    exit 1
fi

# ── Step 6: Push to HuggingFace Space ─────────────────────────────
echo ""
echo "🤗 Step 6: Pushing to HuggingFace Space..."

# Check if HF_TOKEN is set
if [ -z "$HF_TOKEN" ]; then
    echo "⚠️  HF_TOKEN environment variable not set"
    echo "To push to HuggingFace Space, set HF_TOKEN:"
    echo "  export HF_TOKEN=your_token_here"
    echo "  ./restore_tia_core.sh"
    echo ""
    echo "Or manually push:"
    echo "  cd ${WORK_DIR}/${REPO_NAME}"
    echo "  git remote add hf https://huggingface.co/spaces/${HF_ORG}/${REPO_NAME}"
    echo "  git push --force hf main"
else
    # Add HuggingFace remote with token
    git remote add hf "https://${HF_ORG}:${HF_TOKEN}@huggingface.co/spaces/${HF_ORG}/${REPO_NAME}" 2>/dev/null || true
    
    if git push --force hf main; then
        echo "✅ Pushed to HuggingFace Space successfully"
        echo "🔄 HuggingFace Space rebuild triggered"
    else
        echo "❌ Failed to push to HuggingFace Space"
        echo "Check your HF_TOKEN and permissions"
        exit 1
    fi
fi

# ── Step 7: Monitor Build Status ──────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "✅ RESTORATION COMPLETE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 Next Steps:"
echo "  1. Monitor HuggingFace Space build logs:"
echo "     https://huggingface.co/spaces/${HF_ORG}/${REPO_NAME}/logs"
echo ""
echo "  2. Watch for successful installation:"
echo "     - Successfully installed pandas-2.2.x numpy-2.x.x"
echo "     - Running on local URL: http://0.0.0.0:7860"
echo "     - No ModuleNotFoundError messages"
echo ""
echo "  3. Access the Streamlit UI (once build completes):"
echo "     https://huggingface.co/spaces/${HF_ORG}/${REPO_NAME}"
echo ""
echo "  4. Verify all tabs are functional:"
echo "     - T.I.A. Oracle"
echo "     - RAG Store"
echo "     - Districts"
echo "     - Models"
echo "     - Workers"
echo ""
echo "Repository location: ${WORK_DIR}/${REPO_NAME}"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Weld. Pulse. Ignite."
echo "═══════════════════════════════════════════════════════════"
