#!/usr/bin/env python3
"""
Generate TREE.md - District file tree structure
This is a placeholder that can be customized per District
"""
import os
import sys
from datetime import datetime, timezone

def generate_tree(root_path="."):
    """Generate file tree structure."""
    output = []
    output.append("# District File Tree")
    output.append("")
    output.append(f"**Generated**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    output.append(f"**Repository**: {os.environ.get('GITHUB_REPOSITORY', 'Unknown')}")
    output.append("")
    output.append("## Structure")
    output.append("")
    output.append("```")
    
    # Walk directory tree (exclude .git and common cache dirs)
    exclude_dirs = {'.git', '__pycache__', 'node_modules', '.venv', 'venv', 'rag_store'}
    
    for root, dirs, files in os.walk(root_path):
        # Filter out excluded directories
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        
        level = root.replace(root_path, '').count(os.sep)
        indent = ' ' * 2 * level
        output.append(f'{indent}{os.path.basename(root)}/')
        
        subindent = ' ' * 2 * (level + 1)
        for file in sorted(files):
            if not file.startswith('.'):
                output.append(f'{subindent}{file}')
    
    output.append("```")
    output.append("")
    output.append("---")
    output.append("*Generated by Bridge Agent - Citadel Sovereign Protocol*")
    
    return '\n'.join(output)

if __name__ == "__main__":
    print(generate_tree())
